### ISSUE TITLE
Priority: Eventually label is not being picked up for triage

### ISSUE THREAD

**Issue by mjwilson-google** [speced/spec-maintenance#80]
In the WebAudio repository, we added a [Priority: Eventually label](https://github.com/WebAudio/web-audio-api/labels/Priority%3A%20Eventually) with the correct background color.

However, we still get the "This repository doesn't have the Priority: Eventually label" message on the [spec-maintenance page](https://speced.github.io/spec-maintenance/WebAudio/web-audio-api/).

I think this is because in the check [here](https://github.com/speced/spec-maintenance/blob/main/scanner/slo.ts#L31) in slo.tls it is checking `labelNode.name === PRIORITY_EVENTUALLY` and `PRIORITY_EVENTUALLY` is [defined as](https://github.com/speced/spec-maintenance/blob/main/scanner/slo.ts#L9) `"priority: eventually"` (lower case P and E). 
 `toLowerCase()` should probably be run on the name before comparing it instead, as [done above in the same file for Needs Reporter Feedback](https://github.com/speced/spec-maintenance/blob/main/scanner/slo.ts#L14).

I'm not sure if the other calls to `labels.includes` calls are case-sensitive or not but that may also be worth looking at.

**Comment by mjwilson-google** [comment]
It looks like `labels` is constructed with lower-case strings, so there shouldn't be an issue there.  I raised a pull request to resolve `PRIORITY_EVENTUALLY`.

**Comment by jyasskin** [comment]
Still not fixed... To test, you can:
1. Run `pnpm scan --gh-token '$A_GH_TOKEN' --repos WebAudio/web-audio-api`, with a token generated from https://github.com/settings/personal-access-tokens/new.
1. Run `pnpm dev` to see the UI.

**Comment by mjwilson-google** [comment]
Sorry it didn't work, and thank you for the test instructions.  I probably won't have time to look at this again for a while, but I will test first next time.

**Comment by mjwilson-google** [comment]
I tried running it locally with the commands above (I didn't need to generate a token) and it showed "Labels present" for me.  Could you please check one more time?  Or we can wait until next week for the regular scan.

**Comment by mjwilson-google** [comment]
It seems like it's fixed on the public site now too: https://speced.github.io/spec-maintenance/WebAudio/web-audio-api/

**Comment by jyasskin** [comment]
Thank you for following up! I'd forgotten which parts of the scan get cached for a day, and clearly this was one of those.
